inherit_from: .rubocop_todo.yml

inherit_gem:
  rubocop-rock: defaults.yml

AllCops:
    TargetRubyVersion: "2.5"
    Exclude:
    - lib/autobuild/packages/genom.rb
    - vendor/**/*
    - pkg/**/*

Naming/FileName:
    Exclude:
      - lib/autobuild/import/git-lfs.rb

Metrics/ParameterLists:
    Enabled: false

Naming/MethodParameterName:
    AllowedNames: [io, id, to, by, on, in, at, ip, db, ws]
